[package]
name = "perfumer"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
scraper = "0.19.0"
serde = "1.0.202"
tokio = { version = "1.37.0", features = ["full"] }
